/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 classroom.glb --transform 
Files: classroom.glb [44.04MB] > C:\Users\jeet2\OneDrive\Desktop\Hack4Bangla\Mentrix\Metaverse\public\models\classroom-transformed.glb [1.06MB] (98%)
Author: volvor (https://sketchfab.com/volvor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-japanese-school-classroom-d9fc039ba0b6433db91ec129abe86b52
Title: The Japanese School Classroom
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Classroom(props) {
  const { nodes, materials } = useGLTF('/models/classroom.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.School_desk_School_desk_0.geometry} material={materials.School_desk} position={[-2.828, 0, -1.796]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Teacher_desk_Teacher_desk_0.geometry} material={materials.Teacher_desk} position={[2.233, 0, -2.113]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Roof_Roof_0.geometry} material={materials.Roof} position={[-2.599, 3.333, 2.167]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Wall_Wall_0.geometry} material={materials.Wall} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Floor_Floor_0.geometry} material={materials.Floor} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Windows_Windows_0.geometry} material={materials.Windows} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.School_blackboards_School_blackboards_0.geometry} material={materials.School_blackboards} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Book_shell_Book_shell_0.geometry} material={materials.Book_shell} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/classroom.glb')
