/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Student2.glb --transform 
Files: Student2.glb [31.27MB] > C:\Users\jeet2\OneDrive\Desktop\Hack4Bangla\Mentrix\Metaverse\public\models\Student2-transformed.glb [482.21KB] (98%)
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Student2(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/student2-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions,names } = useAnimations(animations, group)
   useEffect(() => {
      // Check and play the first animation (or "sitting" if it's named)
      const animationName = names.find(name => name.toLowerCase().includes("sit")) || names[0]
      if (actions && animationName) {
        actions[animationName].reset().fadeIn(0.5).play()
      }
    }, [actions, names])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
        </group>
        <skinnedMesh name="Ch46" geometry={nodes.Ch46.geometry} material={materials.Ch46_body} skeleton={nodes.Ch46.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/student2-transformed.glb')
