/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 student1.glb --transform 
Files: student1.glb [2.53MB] > C:\Users\jeet2\OneDrive\Desktop\Hack4Bangla\Mentrix\Metaverse\public\models\student1-transformed.glb [416.4KB] (84%)
Author: Patricio Mariano (https://sketchfab.com/patomariano)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/avatar-full-body-ready-player-me-pmariano-a9c1f5d2cd7c4ca3bb46272998d3e451
Title: Avatar Full body - Ready Player Me - pmariano
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Student1(props) {
  const { scene } = useGLTF('/models/student1.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.Object_7.skeleton} />
      <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.Object_9.skeleton} />
      <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Object_11.skeleton} />
      <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.Wolf3D_Glasses} skeleton={nodes.Object_13.skeleton} />
      <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Object_15.skeleton} />
      <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Object_17.skeleton} />
      <skinnedMesh geometry={nodes.Object_19.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Object_19.skeleton} />
      <skinnedMesh geometry={nodes.Object_21.geometry} material={materials['Wolf3D_Shoes.001']} skeleton={nodes.Object_21.skeleton} />
      <skinnedMesh geometry={nodes.Object_23.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Object_23.skeleton} />
      <skinnedMesh geometry={nodes.Object_25.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Object_25.skeleton} />
    </group>
  )
}

useGLTF.preload('/models/student1.glb')
